### ISSUE TITLE
Thémer les nodes "Actualité"

### ISSUE THREAD

**Issue by jabberwooki** [jabberwooki/refuges2#31]
From refuges created by [sographik](https://github.com/sographik) : jabberwooki/refuges#30

**Comment by sographik** [comment]
@jabberwooki voir comment mettre le champs addtoany sous le titre dans le template de page.
@ctardivet faut-il garder l'image de couverture de l'actualité dans la page de l'actualité

**Comment by jabberwooki** [comment]
@sographik C'est fait. Le champ AddToAny est maintenant sous le titre dans les nodes Actualité.
Attention ! Il faut passer la couleur des pictos en blanc pour qu'ils soient bien visibles.

[INFOS DEV]
C'était plus difficile que prévu. Impossible de trouver comment récupérer la valeur du champ addtoany dans le template. La solution utilisée est la suivante : 
1) dans le fichier refuges.theme, function refuges_preprocess_page(), j'utilise du pur code Drupal 8 pour générer une instance de bloc AddToAny (heureusement pour moi, le module AddToAny fournit un bloc). Je passe le contenu de cette instance au template page--type--news.tpl.php à l'aide de la variable **addtoany_buttons**.
2) dans le template je me contente d'afficher les buttons addtoany à l'endroit voulu juste avec l'instruction twig **{{ addtoany_buttons }}**.
3) dans le paramétrage display suite du type de contenu Actualité, je retire le champ AddToAny de l'affichage dans le mode Contenu complet.
