### ISSUE TITLE
problème affichage menu admin refuge orgere

### ISSUE THREAD

**Issue by ctardivet** [jabberwooki/refuges2#49]
le menu admin est éclaté lorsque j'essaye de créer une diapositive
![capture d ecran 2018-10-30 09 56 04](https://user-images.githubusercontent.com/39907379/47706644-0bd44d00-dc2a-11e8-8e51-b7398a4ca617.png)

**Comment by jabberwooki** [comment]
Cause du problème : erreur technique très probablement dans un fichier javascript compilé.
Solution classique : vidage complet des caches Drupal et tout est rentré dans l'ordre.
