### ISSUE TITLE
problème affichage menu hamburger refuge orgere

### ISSUE THREAD

**Issue by ctardivet** [jabberwooki/refuges2#50]
le menu secondaire du menu séjourner ne s'affiche pas au premier déploiement du menu hamburger mais que après avoir cliquer sur séjourner puis être revenu en arrière.
![capture d ecran 2018-10-30 10 01 49](https://user-images.githubusercontent.com/39907379/47707151-615d2980-dc2b-11e8-92c5-cf959711e66f.png)
![capture d ecran 2018-10-30 10 02 04](https://user-images.githubusercontent.com/39907379/47707170-70dc7280-dc2b-11e8-8334-c3fa0d361833.png)

**Comment by jabberwooki** [comment]
OK. Je traite.

**Comment by jabberwooki** [comment]
Corrigé. Le problème venait du fait que le lien de premier niveau **Séjourner** n'était pas complètement paramétré.
Pour qu'un lien de menu montre qu'il possède des sous-liens, il faut que sa case _Show as expanded_ (entourée en rouge ci-dessous) soit cochée.

![parametrages-lien-menu](https://user-images.githubusercontent.com/1741337/47773800-90d36b00-dceb-11e8-8aba-7b6452d8d8df.png)
