### ISSUE TITLE
problème de vue sur la saisie dans l'éditeur de texte

### ISSUE THREAD

**Issue by ctardivet** [jabberwooki/refuges2#52]
on ne voit pas en temps réel les styles appliqués dans l'éditeur de texte

**Comment by jabberwooki** [comment]
Corrigé en création le module custom Utilitaires Refuges (package Refuges) et en implémentant le hook_ckeditor_css_alter() pour permettre à Ckeditor d'utiliser la feuille de style du site.

**Comment by jabberwooki** [comment]
Déployé mardi 13/11/18.
