### ISSUE TITLE
Lien Télécharger - page Documents

### ISSUE THREAD

**Issue by sographik** [jabberwooki/refuges2#56]
@jabberwooki : refuges2\web\themes\contrib\bootstrap\templates\file\file-link.html.twig, il faut faire une suggestion de template pour ce champs.
Ainsi on pourra forcer l'affichage de "Télécharger" au lieu du nom de fichier et également mettre le poids du document au dessus de l'îcone.

**Comment by jabberwooki** [comment]
@sographik J'ai copié le template file-link.html.twig dans le dossier /templates du thème custom refuges et je l'ai customisé. 
- Le mot "Télécharger" s'affiche maintenant à la place de la description du fichier (c'est la description, pas le nom, qui s'affichait précédemment - voir le paramétrage display suite du champ Télécharger).
- Le poids du fichier est placé au dessus du reste.
