### ISSUE TITLE
bug affichage carroussel

### ISSUE THREAD

**Issue by ctardivet** [jabberwooki/refuges2#61]
Problème d'affichage du carroussel sur les sites de Fond des Fours et La Martin
![capture d ecran 2018-11-28 12 13 19](https://user-images.githubusercontent.com/39907379/49148208-0b050880-f307-11e8-93c2-5bed6ba0d01b.png)

**Comment by sographik** [comment]
@ctardivet les images n'ont pas été recadré, mais peu importe je viens d'apporter des modifications qui seront déployer demain et qui corrige ce type de problème sans avoir à recadrer.
