### ISSUE TITLE
Paramétrage des blocs "Suivez-nous" pour ouverture des liens dans une nouvelle fenêtre

### ISSUE THREAD

**Issue by sographik** [jabberwooki/refuges2#72]
Aller dans Structure > Mise en page des blocs puis aller sur Configurer pour le bloc Suivez-nous en région top et en région footer.

Attributs du lien, choisir dans la liste déroulante de Default target : Open in a new window or tab (_blank) puis en bas de page cliquer sur "Enregistrer"

Opération à faire pour les 2 blocs "Suivez-nous"

Je ne sais pas si Chloé à les droits pour le faire ou pas.

**Comment by jabberwooki** [comment]
Réponse : oui.
Après vérification sur un site de prod, Chloé a les droits pour pouvoir effectuer la modification décrite.
